<script setup lang="ts">
import WikiRoot from './WikiRoot.vue';
</script>

<template>
  <WikiRoot title="Cycloid">
    <p>
      In geometry, a cycloid is the curve traced by a point on a circle as it rolls along a straight line without
      slipping. A cycloid is a specific form of trochoid and is an example of a roulette, a curve generated by a curve
      rolling on another curve.
    </p>

    <p>
      The cycloid, with the cusps pointing upward, is the curve of fastest descent under uniform gravity (the
      brachistochrone curve). It is also the form of a curve for which the period of an object in simple harmonic motion
      (rolling up and down repetitively) along the curve does not depend on the object's starting position (the
      tautochrone curve). In physics, when a charged particle at rest is put under a uniform electric and magnetic field
      perpendicular to one another, the particle’s trajectory draws out a cycloid.
    </p>

    <h2>Equations</h2>
    <p>
      The cycloid through the origin, generated by a circle of radius r rolling over the x-axis on the positive side
      <code>(y ≥ 0)</code>, consists of the points <code>(x, y)</code>, with
    </p>
    <pre class="whitespace-pre-line">
      <code>
        x = r ( t − sin(t) )
        y = r ( 1 − cos(t) )
      </code>
    </pre>
    <p>
      where t is a real parameter corresponding to the angle through which the rolling circle has rotated. For given t,
      the circle's centre lies at <code>(x, y) = (rt, r)</code>.
    </p>
    <p>The Cartesian equation is obtained by solving the y-equation for t and substituting into the x-equation:</p>
    <pre class="whitespace-pre-line">
      <code>
        x = r cos⁻¹( 1 − ( y / r )) − √(y (2r − y))
      </code>
    </pre>
    <p>or, eliminating the multiple-valued inverse cosine:</p>
    <pre class="whitespace-pre-line">
      <code>
        r cos( x + √( y ( 2r − y )) / r ) + y = r
      </code>
    </pre>
  </WikiRoot>
</template>

<style scoped></style>
