<script setup lang="ts">
import WikiRoot from '@/components/wiki/WikiRoot.vue';
</script>

<template>
  <WikiRoot title="Hypocycloid">
    <p>
      In geometry, a hypocycloid is a special plane curve generated by the trace of a fixed point on a small circle that
      rolls within a larger circle. As the radius of the larger circle is increased, the hypocycloid becomes more like
      the cycloid created by rolling a circle on a line.
    </p>
    <h3>Equations</h3>
    <p>
      If the smaller circle has radius r, and the larger circle has radius R = kr, then the parametric equations for the curve can be given by either:
    </p>
    <pre class="whitespace-pre-line">
      <code>
       x(θ) = (R - r) cos(θ) + r cos((R - r / r )θ)
       y(θ) = (R - r) sin(θ) − r sin((R - r / r )θ)
     </code>
    </pre>
    or:
    <pre class="whitespace-pre-line">
      <code>
        x(θ) = r(k - 1) cos(θ) + r cos((k - 1)θ)
        y(θ) = r(k - 1) sin(θ) − r sin((k - 1)θ)
      </code>
    </pre>
  </WikiRoot>
</template>

<style scoped></style>
